services:
  - type: web
    name: uiitlabxpert-frontend
    env: static
    buildCommand: npm install && npm run build:prod
    staticPublishPath: "./build"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"