services:
  - type: web
    name: uiitlabxpert-frontend
    env: static  # ← Must be "static" for React SPAs
    buildCommand: npm install && npm run build
    staticPublishPath: "./build"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"